// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmgziqpedfrfuvoaiyaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZ3ppcXBlZGZyZnV2b2FpeWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjAyMDEsImV4cCI6MjA2MTQzNjIwMX0.UoHz1ZPbNG5RnwraksYH1NxYAFtQwyEgNThkZGoS-tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);